# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  app1:
    image: app:latest
    ports:
      - "5001:5000"

  app2:
    image: app:latest
    ports:
      - "5002:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
